Repository IgKniteDev/IgKnite, pull requests merged in 2022-12, with the labels that each got.

#152 bugfix: `/ripplepurge` backend message and error handler
  cogs/exceptionhandler.py
  cogs/moderation.py
Labels: bug-fixed

#156 bugfix: role lock `/revokeinvites`
  cogs/inspection.py
Labels: bug-fixed

#157 chore: synchronization PR
  core/__init__.py
Labels: tuning

#160 chore: reused webhooks for similar users
  cogs/moderation.py
Labels: tuning

#161 bugfix: AttributeError
  cogs/moderation.py
Labels: bug-fixed

#162 chore: Properly reused webhooks inside `/snipe` command
  cogs/moderation.py
  core/__init__.py
Labels: tuning

#164 feat: Add a new option to the `/purge` slash command
  cogs/moderation.py
  core/__init__.py
  pre-commit-config.yaml
Labels: tuning, feat
