Repository IgKniteDev/IgKnite, pull requests merged in 2022-11, with the labels that each got.

#144 feat: added `/showbannedwords`
  cogs/moderation.py
Labels: commands, feat

#147 bug-fixed: Rich presence tweaks and more.
  Dockerfile
  core/bot.py
  requirements.txt
Labels: tuning, bug-fixed

#148 Using embeds on errors! (in cogs/moderation.py)
  cogs/moderation.py
  core/embeds.py
Labels: tuning

#149 feat: Added `/clearnicks` slash command.
  cogs/moderation.py
Labels: commands, feat
