Repository IgKniteDev/IgKnite, pull requests merged in 2022-10, with the labels that each got.

#42 replace queue string to select option
  cogs/music.py
Labels: commands, feat, hacktoberfest-accepted

#43 Added dependabot & resolved dependencies.
  .github/dependabot.yml
  cogs/music.py
  requirements.txt
Labels: tuning

#49 feat(#40): implement invites command
  cogs/inspection.py
Labels: commands, feat, hacktoberfest-accepted

#54 Merge incoming changes
  cogs/inspection.py
Labels: commands, bug-fixed, hacktoberfest-accepted

#51 Fixed /now command not updating after audio is finished.
  cogs/music.py
Labels: commands, bug-fixed, hacktoberfest-accepted

#56 Resolved error handling for `/play` slash command.
  cogs/music.py
Labels: bug-fixed, hacktoberfest-accepted

#58 Added skip and volume buttons to the `/now` slash command.
  cogs/music.py
Labels: tuning, commands, hacktoberfest-accepted

#63 Switch to min & max value validation built-into Discord
  cogs/customization.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
Labels: tuning, hacktoberfest-accepted

#66 feat : New issue templates 🛠
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: tuning, hacktoberfest-accepted

#72 Add /reset command for wiping text channels.
  .gitignore
  .vscode/settings.json
  cogs/customization.py
Labels: commands, feat, hacktoberfest-accepted

#77 Removed Hardcoded License
  cogs/customization.py
  cogs/exceptionhandler.py
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
  core/__init__.py
  core/bot.py
  core/datacls.py
  core/embeds.py
  core/global_.py
  main.py
Labels: docs, hacktoberfest-accepted

#79 Embed contributors' images into markdown.
  README.md
Labels: docs, hacktoberfest-accepted

#80 Add informative fields to the `/ping` slash command.
  cogs/general.py
Labels: commands, feat, hacktoberfest-accepted

#84 Fixed view appearing after timeout.
  cogs/music.py
Labels: bug-fixed, hacktoberfest-accepted

#85 Added license reference to markdown.
  README.md
Labels: docs, hacktoberfest-accepted

#86 GitHub Actions tweaks and substantially changed markdown.
  .github/workflows/deploy.yml
  README.md
  static/now_command_demo.png
Labels: docs, tuning, hacktoberfest-accepted

#87 Added more to `/ping`
  cogs/general.py
  core/global_.py
Labels: commands, feat, hacktoberfest-accepted

#89 Add a message command equivalent to `/play`.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  cogs/music.py
Labels: commands, feat

#90 Fixed broken "Search & Play", a colorful shuffle & more!
  cogs/inspection.py
  cogs/music.py
Labels: tuning, commands, bug-fixed

#91 Squished some bugs in the Music cog, patched `/volume` and more.
  cogs/music.py
Labels: tuning, commands, bug-fixed

#93 Added a refresh button to the `/ping` slash command.
  cogs/general.py
Labels: commands, feat, hacktoberfest-accepted

#94 Modifications to the newly added `/ping` command and more.
  .github/ISSUE_TEMPLATE/feature_request.yml
  cogs/general.py
  cogs/inspection.py
  cogs/music.py
  core/__init__.py
  core/embeds.py
  core/global_.py
Labels: tuning, commands

#95 Tuning of `/queue` (Remove and Play buttons)
  cogs/music.py
Labels: commands, feat, hacktoberfest-accepted

#96 Fine-tuned the tuned `/queue` command, reduced boilerplate and more.
  .github/pull_request_template.md
  cogs/music.py
Labels: tuning, commands

#100 Add commands documentation
  .gitignore
  docs/README.md
Labels: docs, hacktoberfest-accepted

#101 Added: `/senddm`
  cogs/moderation.py
Labels: commands, feat, hacktoberfest-accepted

#102 Added `/playrich` and patched Spotify handler.
  cogs/music.py
Labels: commands, feat, bug-fixed

#103 Improved `/playrich` command family and implemented Docker Compose.
  Dockerfile
  cogs/general.py
  cogs/music.py
  docker-compose.yml
Labels: tuning, commands

#105 Added a new `/help` slash command.
  cogs/general.py
  core/global_.py
Labels: commands, feat, hacktoberfest-accepted

#104 Issue #59 Update Exception Handler
  cogs/exceptionhandler.py
Labels: tuning, hacktoberfest-accepted

#107 Fixed issues from previous PRs and updated the `/ping` slash command.
  .flake8
  cogs/exceptionhandler.py
  cogs/general.py
  cogs/music.py
  core/__init__.py
  core/global_.py
Labels: tuning, bug-fixed

#108 Fixed refreshing of selection field in the `/queue` slash command.
  cogs/music.py
Labels: commands, bug-fixed, hacktoberfest-accepted

#110 Fixed bugs with `core.embeds.TypicalView` and renamed it.
  cogs/general.py
  cogs/music.py
  core/embeds.py
Labels: tuning, bug-fixed

#113 Improved CI/CD and Docker Compose workflows for fly.io deployment.
  .github/workflows/linting.yml
  Dockerfile
  docker-compose.yml
Labels: tuning

#114 Added Black without string normalization and implemented automations for it.
  .github/workflows/linting.yml
  cogs/customization.py
  cogs/exceptionhandler.py
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
  core/__init__.py
  core/bot.py
  core/embeds.py
  core/global_.py
  main.py
Labels: tuning, feat

#117 Add pins related commands
  cogs/moderation.py
Labels: commands, feat, hacktoberfest-accepted

#119 Fixed formatting errors from newest PR and improved automation.
  .github/workflows/linting.yml
  cogs/moderation.py
  core/__init__.py
Labels: tuning, commands, hacktoberfest-accepted

#120 Add color option to /makerole
  cogs/customization.py
Labels: tuning, commands, hacktoberfest-accepted

#123 Added new `/revokeinvites` slash command.
  cogs/inspection.py
Labels: commands, feat

#125 feat: /slowmode and /noslomo
  cogs/moderation.py
Labels: commands, feat, hacktoberfest-accepted

#127 Added choices to `/slowmode` and separated workflows.
  .github/workflows/formatting.yml
  .github/workflows/linting.yml
  cogs/moderation.py
Labels: tuning, commands

#131 refact: use or operator instead of ternay
  cogs/general.py
  cogs/inspection.py
  cogs/music.py
Labels: tuning, hacktoberfest-accepted

#132 Add /banword
  cogs/moderation.py
Labels: commands, feat, hacktoberfest-accepted

#134 chore: Improved formatting using included project configuration and more.
  .flake8
  .github/workflows/formatting.yml
  cogs/customization.py
  cogs/exceptionhandler.py
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
  core/bot.py
  core/embeds.py
  docker-compose.yml
  pyproject.toml
Labels: tuning

#135 chore: Improved `/banword`, refactored codebase parts.
  .vscode/settings.json
  cogs/customization.py
  cogs/exceptionhandler.py
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
  core/__init__.py
  core/embeds.py
  core/global_.py
  main.py
Labels: tuning

#136 feat: Added new KeyChain utility for managing environments.
  cogs/general.py
  cogs/moderation.py
  cogs/music.py
  core/__init__.py
  core/bot.py
  core/chain.py
  core/global_.py
  main.py
Labels: tuning, feat

#137 add /afkvc
  cogs/customization.py
Labels: commands, feat, hacktoberfest-accepted

#139 refactor: Updated bot model and the `/afkvc` slash command.
  cogs/customization.py
  core/bot.py
Labels: tuning, commands, hacktoberfest-accepted

#140 feat: Added `/clearbannedwords`, refactored `/banword` slash command.
  cogs/moderation.py
Labels: tuning, commands, feat

#141 feat: report button in exception handler
  cogs/exceptionhandler.py
Labels: feat, hacktoberfest-accepted
