Repository IgKniteDev/IgKnite, pull requests merged in 2022-08, with the labels that each got.

#3 Role locks, random footers & more!
  cogs/inspection.py
  core/dataclasses.py
  core/embeds.py
Labels: enhancement

#7 Placed the primary class for bot inside the core package.
  .flake8
  core/__init__.py
  core/bot.py
  main.py
Labels: enhancement

#9 Standardized README.md
  README.md
Labels: documentation

#11 `Moderation` cog & new commands
  cogs/moderation.py
Labels: enhancement

#12 Fixed type hinting at some places.
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
Labels: enhancement

#13 Set `required` to `True` for some options!
  cogs/moderation.py
Labels: enhancement

#14 Implemented all **purge** related commands
  cogs/moderation.py
Labels: enhancement

#15 Added `/audit`, modified type hints and more.
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  core/__init__.py
Labels: enhancement

#16 Add # before command decorators.
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
Labels: tuning

#18 Added `/softban`, `/timeout`, `/snipe` and more!
  README.md
  cogs/moderation.py
  core/bot.py
  core/global_.py
Labels: tuning, commands

#20 GUI tool & more
  cogs/inspection.py
  cogs/moderation.py
  core/__init__.py
  core/datacls.py
  core/guicer.py
  requirements.txt
Labels: tuning, feat

#21 Migration to discord.py, more juicier 'guicer' and more.
  .flake8
  README.md
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  core/__init__.py
  core/bot.py
  core/embeds.py
  core/global_.py
  guicer.py
  main.py
  requirements.txt
Labels: tuning

#22 Fixed critical bug regarding global variable declarations.
  README.md
  cogs/general.py
  cogs/inspection.py
  core/global_.py
Labels: docs, bug-fixed

#23 What are you doing? **Docking.**
  Dockerfile
  README.md
  core/bot.py
  core/global_.py
  main.py
  requirements.txt
Labels: docs, tuning, feat

#26 `Customization` cog & new commands!
  cogs/customization.py
  cogs/exceptionhandler.py
  main.py
Labels: feat

#27 Refined exception handling, no more error jokes and more.
  cogs/exceptionhandler.py
  core/bot.py
  core/embeds.py
  main.py
Labels: tuning, feat

#28 Restructured method declarations.
  cogs/customization.py
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  core/bot.py
  core/decor.py
Labels: tuning

#30 Music system foundation and one intentional, little change.
  Dockerfile
  cogs/customization.py
  cogs/music.py
  core/__init__.py
  core/bot.py
  core/global_.py
  main.py
  requirements.txt
Labels: invalid, commands, feat
