Repository IgKniteDev/IgKnite, pull requests merged in 2023-02, with the labels that each got.

#171 [tuning] Fixed YTDL playback issue and reverted typing changes.
  .gitignore
  cogs/customization.py
  cogs/moderation.py
  cogs/music.py
  core/bot.py
  fly.toml
  requirements.txt
Labels: tuning, bug-fixed

#173 [chore] Added concurrency to the GitHub Actions workflows.
  .github/workflows/deploy.yml
  .github/workflows/formatting.yml
  .github/workflows/linting.yml
Labels: tuning

#179 Add `/loop` & `/shuffle` commands
  cogs/music.py
Labels: commands, feat

#182 [chore] Added dev container support for Docker and more
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  README.md
  cogs/music.py
  core/__init__.py
  core/ui/__init__.py
  static/now_command_demo.png
  static/play_command_demo.png
Labels: tuning, commands

#184 (tuning) Snipes are now ordered
  cogs/moderation.py
Labels: tuning, commands

#186 [tuning] Better overall `/snipe` command operation and more
  cogs/moderation.py
  cogs/music.py
  core/chain.py
Labels: tuning, commands
