Repository IgKniteDev/IgKnite, pull requests merged in 2023-03, with the labels that each got.

#187 📝 (chore) Updated contribution guidelines
  CONTRIBUTING.md
  core/__init__.py
Labels: docs

#188 [dependency] Updated requirements.txt
  .github/dependabot.yml
  requirements.txt
Labels: dependency

#189 :art: [tuning] Formatted codebase and such
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
Labels: tuning

#192 :zap: [tuning] Improved base for several slash commands
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
Labels: tuning, commands

#193 ✨ [tuning] Added "Clear Queue" button and a new random footer
  cogs/music.py
  core/embeds.py
Labels: tuning, feat

#194 ✨ [feat] Added improved viewing for `/queue`, improved codebase and more
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
  core/embeds.py
Labels: tuning, commands, feat

#196 :bug: Fixed `/volume` command bug, reordered file structure and more
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  cogs/music.py
  core/__init__.py
Labels: tuning, bug-fixed

#198 :bug: [bug-fixed] Fixed bug with `/resume` command and more
  cogs/music.py
Labels: tuning, commands, bug-fixed

#201 ✨ [feat] Added new listener for emoji reactions, bookmarking feature
  cogs/general.py
Labels: feat

#203 🔨 [tuning] Better embeds and views, bookmark improvements
  cogs/general.py
  core/embeds.py
Labels: tuning

#205 🐛 [bug-fixed] Fix author name on bookmark embed
  cogs/general.py
Labels: bug-fixed

#207 🐛 [bug-fixed] Resolved incorrect voice safety
  cogs/music.py
  core/__init__.py
Labels: bug-fixed

#208 🐛 [bug-fixed] Fixed manual disconnect / kick bug and more
  cogs/music.py
Labels: feat, bug-fixed

#210 🎨 [tuning] Improved code syntax in some areas
  cogs/customization.py
  cogs/general.py
  cogs/inspection.py
  cogs/moderation.py
  cogs/music.py
  core/__init__.py
  core/ui.py
Labels: tuning

#211 🐛 [bug-fixed] Fixed voice state update bugs and updated documents
  LICENSE
  README.md
  cogs/music.py
  core/__init__.py
  static/banner.png
  static/logo_circle.png
  static/now_command_demo.png
  static/play_command_demo.png
Labels: tuning, bug-fixed

#214 🔨 [tuning] Better voice safety checks
  cogs/music.py
  core/__init__.py
Labels: tuning
